feat: redemption and reallocation of nomad collateral and protocol reserves for FRAX Market Enhancement (proposal 2)
moonwell-fi/mtoken-fixes pull request #1
Opened 2024-01-19 17:35 UTC by bsolid

## Overview

As per the RFP, this PR contains the second proposal for addressing the bad Nomad debt.

## Contract Diffs

Contract diffs can be found [here](https://github.com/moonwell-fi/mtoken-fixes/pull/1/commits/c0f00e8ada0d7787df61cd55f7e324d7e45e18cb?file-filters%5B%5D=.diff&show-viewed-files=true), to verify that these contracts match exactly what is deployed.

## Slither Slot Verification

### Contracts

#### `MErc20Delegate.sol`

Run: `slither src/MErc20Delegate.sol --print variable-order` to generate the output:

```
INFO:Printers:
ComptrollerInterface:
+--------------------------------+--------+------+--------+
|              Name              |  Type  | Slot | Offset |
+--------------------------------+--------+------+--------+
| ComptrollerInterface.gasAmount | uint16 |  0   |   0    |
+--------------------------------+--------+------+--------+

EIP20Interface:
+------+------+------+--------+
| Name | Type | Slot | Offset |
+------+------+------+--------+
+------+------+------+--------+

EIP20NonStandardInterface:
+------+------+------+--------+
| Name | Type | Slot | Offset |
+------+------+------+--------+
+------+------+------+--------+

ComptrollerErrorReporter:
+------+------+------+--------+
| Name | Type | Slot | Offset |
+------+------+------+--------+
+------+------+------+--------+

InterestRateModel:
+------+------+------+--------+
| Name | Type | Slot | Offset |
+------+------+------+--------+
+------+------+------+--------+

MErc20Delegate:
+-------------------------------------------+--------------------------------------------------+------+--------+
|                    Name                   |                       Type                       | Slot | Offset |
+-------------------------------------------+--------------------------------------------------+------+--------+
|         MTokenStorage._notEntered         |                       bool                       |  0   |   0    |
|             MTokenStorage.name            |                      string                      |  1   |   0    |
|            MTokenStorage.symbol           |                      string                      |  2   |   0    |
|           MTokenStorage.decimals          |                      uint8                       |  3   |   0    |
|            MTokenStorage.admin            |                     address                      |  3   |   1    |
|         MTokenStorage.pendingAdmin        |                     address                      |  4   |   0    |
|         MTokenStorage.comptroller         |               ComptrollerInterface               |  5   |   0    |
|      MTokenStorage.interestRateModel      |                InterestRateModel                 |  6   |   0    |
| MTokenStorage.initialExchangeRateMantissa |                     uint256                      |  7   |   0    |
|    MTokenStorage.reserveFactorMantissa    |                     uint256                      |  8   |   0    |
|    MTokenStorage.accrualBlockTimestamp    |                     uint256                      |  9   |   0    |
|         MTokenStorage.borrowIndex         |                     uint256                      |  10  |   0    |
|         MTokenStorage.totalBorrows        |                     uint256                      |  11  |   0    |
|        MTokenStorage.totalReserves        |                     uint256                      |  12  |   0    |
|         MTokenStorage.totalSupply         |                     uint256                      |  13  |   0    |
|        MTokenStorage.accountTokens        |           mapping(address => uint256)            |  14  |   0    |
|      MTokenStorage.transferAllowances     | mapping(address => mapping(address => uint256))  |  15  |   0    |
|        MTokenStorage.accountBorrows       | mapping(address => MTokenStorage.BorrowSnapshot) |  16  |   0    |
|  MTokenStorage.protocolSeizeShareMantissa |                     uint256                      |  17  |   0    |
|          MErc20Storage.underlying         |                     address                      |  18  |   0    |
|     MDelegationStorage.implementation     |                     address                      |  19  |   0    |
+-------------------------------------------+--------------------------------------------------+------+--------+

MDelegatorInterface:
+-----------------------------------+---------+------+--------+
|                Name               |   Type  | Slot | Offset |
+-----------------------------------+---------+------+--------+
| MDelegationStorage.implementation | address |  0   |   0    |
+-----------------------------------+---------+------+--------+

INFO:Slither:src/MErc20Delegate.sol analyzed (19 contracts)
```

#### `MErc20DelegateFixer.sol`

Run `slither src/MErc20DelegateFixer.sol --print variable-order` to generate the output:

```
INFO:Printers:
ComptrollerInterface:
+--------------------------------+--------+------+--------+
|              Name              |  Type  | Slot | Offset |
+--------------------------------+--------+------+--------+
| ComptrollerInterface.gasAmount | uint16 |  0   |   0    |
+--------------------------------+--------+------+--------+

EIP20Interface:
+------+------+------+--------+
| Name | Type | Slot | Offset |
+------+------+------+--------+
+------+------+------+--------+

EIP20NonStandardInterface:
+------+------+------+--------+
| Name | Type | Slot | Offset |
+------+------+------+--------+
+------+------+------+--------+

ComptrollerErrorReporter:
+------+------+------+--------+
| Name | Type | Slot | Offset |
+------+------+------+--------+
+------+------+------+--------+

InterestRateModel:
+------+------+------+--------+
| Name | Type | Slot | Offset |
+------+------+------+--------+
+------+------+------+--------+

MErc20DelegateFixer:
+-------------------------------------------+--------------------------------------------------+------+--------+
|                    Name                   |                       Type                       | Slot | Offset |
+-------------------------------------------+--------------------------------------------------+------+--------+
|         MTokenStorage._notEntered         |                       bool                       |  0   |   0    |
|             MTokenStorage.name            |                      string                      |  1   |   0    |
|            MTokenStorage.symbol           |                      string                      |  2   |   0    |
|           MTokenStorage.decimals          |                      uint8                       |  3   |   0    |
|            MTokenStorage.admin            |                     address                      |  3   |   1    |
|         MTokenStorage.pendingAdmin        |                     address                      |  4   |   0    |
|         MTokenStorage.comptroller         |               ComptrollerInterface               |  5   |   0    |
|      MTokenStorage.interestRateModel      |                InterestRateModel                 |  6   |   0    |
| MTokenStorage.initialExchangeRateMantissa |                     uint256                      |  7   |   0    |
|    MTokenStorage.reserveFactorMantissa    |                     uint256                      |  8   |   0    |
|    MTokenStorage.accrualBlockTimestamp    |                     uint256                      |  9   |   0    |
|         MTokenStorage.borrowIndex         |                     uint256                      |  10  |   0    |
|         MTokenStorage.totalBorrows        |                     uint256                      |  11  |   0    |
|        MTokenStorage.totalReserves        |                     uint256                      |  12  |   0    |
|         MTokenStorage.totalSupply         |                     uint256                      |  13  |   0    |
|        MTokenStorage.accountTokens        |           mapping(address => uint256)            |  14  |   0    |
|      MTokenStorage.transferAllowances   [...]

2024-01-22 17:20 UTC, ElliotFriedman commented on src/MErc20DelegateFixer.sol
> +    function _zeroBalance(address user) internal returns (uint256) {
make function private

2024-01-22 17:22 UTC, ElliotFriedman commented on src/MErc20DelegateFixer.sol
> +        borrowSnapshot.interestIndex = 0;
I don't think there is a need to zero interest index. we can just set it to the latest borrow index.

2024-01-22 17:28 UTC, ElliotFriedman commented
It would be great if you could pull the forge proposal simulator into this repo and test the upgrade. That will make the integration testing a breeze.

2024-01-22 17:32 UTC, ElliotFriedman commented on src/MErc20DelegateFixer.sol
> +        transferTokens(msg.sender, address(user), liquidator, accountTokens[user]);
prefer to update `accountTokens` mapping directly as this call will likely fail as if the user has bad debt, they should not be able to transfer tokens.

2024-01-22 17:32 UTC, ElliotFriedman commented on src/MErc20DelegateFixer.sol
> +        transferTokens(msg.sender, address(user), liquidator, accountTokens[user]);
we should use safemath during these addition and subtraction operations

2024-01-22 18:11 UTC, bsolid commented
> It would be great if you could pull the forge proposal simulator into this repo and test the upgrade. That will make the integration testing a breeze.

Yes, that was the plan 😄

2024-01-22 18:29 UTC, ElliotFriedman commented on src/ComptrollerFixer.sol
> +    address[] public fixMarkets = [0x948CCfff51F894DBA5C250aa2844d58E169f8aD9];
This should contain all .mad asset addresses, as well as all markets with bad debt, FRAX, GLMR and DOT.

2024-01-22 18:30 UTC, ElliotFriedman commented on src/ComptrollerFixer.sol
> +    address[] public fixMarkets = [0x948CCfff51F894DBA5C250aa2844d58E169f8aD9];
Would be great to make this array fixed in size to save in gas during the governance proposal for the DAO

2024-01-24 02:25 UTC, bsolid commented on test/integration/ComptrollerFixer.sol
> +        assertEq(comptrollerFixer.badDebt(address(mwETHMadDelegator)), 0);
Need to check the math on this and the other tests - bad debt should not be `0`.

2024-01-24 02:26 UTC, bsolid commented on test/integration/ComptrollerFixer.sol
> +import "@forge-std/console.sol";
Console is no longer required.

2024-01-24 02:28 UTC, bsolid commented on test/integration/ComptrollerFixer.sol
> +    function testFixUsers_mFRAX() public {
Should test multiple users from the spreadsheet - not just a single user.

2024-01-24 02:28 UTC, bsolid commented on test/integration/ComptrollerFixer.sol
> +    function testFixUsers_mxcDOT() public {
Should test multiple users from the spreadsheet - not just a single user.

2024-01-24 02:28 UTC, bsolid commented on test/integration/ComptrollerFixer.sol
> +    function testFixUsers_mUSDCMad() public {
Should test multiple users from the spreadsheet - not just a single user.

2024-01-24 02:28 UTC, bsolid commented on test/integration/ComptrollerFixer.sol
> +    function testFixUsers_mwETHMad() public {
Should test multiple users from the spreadsheet - not just a single user.

2024-01-24 02:28 UTC, bsolid commented on test/integration/ComptrollerFixer.sol
> +    function testFixUsers_mwBTCMad() public {
Should test multiple users from the spreadsheet - not just a single user.

2024-01-24 02:29 UTC, bsolid commented on src/Interfaces/IComptrollerFixer.sol
> +interface IComptrollerFixer {
Add missing natspec.

2024-01-24 02:29 UTC, bsolid commented on src/Interfaces/IMErc20DelegateFixer.sol
> +interface IMErc20DelegateFixer {
Add missing natspec.

2024-01-24 02:29 UTC, bsolid commented on src/Interfaces/IMErc20Delegator.sol
> +interface IMErc20Delegator {
Add missing natspec.

2024-01-24 06:05 UTC, ElliotFriedman commented
Could you break things out into 2 PR's?

1. is the original code you're merging
2. are the changes to the code and fixer contracts?

this would make it much easier to reason about what is going on here

2024-01-26 00:36 UTC, ElliotFriedman commented on src/MErc20DelegateFixer.sol
> +    function getCashPrior() internal view returns (uint256) {
does this need to be specified as override?

2024-01-26 00:37 UTC, ElliotFriedman commented on src/MErc20DelegateFixer.sol
> +    function getCashPrior() internal view returns (uint256) {
I believe the implementation in MErc20 specifies this is a virtual function, at least in the newer codebase:

`function getCashPrior() virtual override internal view returns (uint)`

2024-01-26 00:37 UTC, ElliotFriedman commented on src/proposals/Addresses.sol
> +contract Addresses is Test {
shouldn't you get this entire file out of the box with FPS that you imported?

2024-01-26 00:38 UTC, ElliotFriedman commented on src/proposals/Addresses.sol
> +
this looks like the older file without all of the checks and safety rails we put into the newer one in FPS. We should use the newer version.

2024-01-26 00:43 UTC, ElliotFriedman commented on src/MErc20DelegateFixer.sol
> +        /// require(msg.sender == admin, "only the admin may call fixUser");
we really need this check to be uncommented, otherwise anyone can arbitrarily seize tokens from users

2024-01-26 00:44 UTC, ElliotFriedman commented on src/MErc20DelegateMadFixer.sol
> +        //require(msg.sender == admin, "only admin may sweep all");
we really need this check to be uncommented, otherwise anyone can arbitrarily sweep tokens from users

2024-01-26 00:45 UTC, ElliotFriedman commented on src/ComptrollerFixer.sol
> +contract ComptrollerFixer {
It's unclear to me why this contract is needed.

It feels like we can get rid of it entirely.

2024-01-26 00:49 UTC, ElliotFriedman commented on src/proposals/mips/mip-m17/mip-m17.sol
> +                );
Instead of doing this, I'm pretty sure we can remove the comptroller fixer contract and build the calldata in a for loop, where we check if a user has bad debt.

If they have bad debt in FRAX. we add a call to the frax fixer contract.

We also check for bad debt in xcDOT. If they do, we add a call to the xcDOT fixer contract.

2024-01-26 00:59 UTC, ElliotFriedman commented
Add a diff using https://www.diffchecker.com/ for all the imported contracts
Slither storage offset checks

2024-01-26 17:50 UTC, bsolid commented on src/ComptrollerFixer.sol
> +contract ComptrollerFixer {
Removed.

2024-01-26 18:02 UTC, bsolid commented on src/MErc20DelegateMadFixer.sol
> +        //require(msg.sender == admin, "only admin may sweep all");
Agreed - was just commented out for testing. Re-enabled now.

2024-01-26 18:02 UTC, bsolid commented on src/MErc20DelegateFixer.sol
> +        /// require(msg.sender == admin, "only the admin may call fixUser");
Agreed - was just commented out for testing. Re-enabled now.

2024-01-26 18:08 UTC, bsolid commented on src/proposals/Addresses.sol
> +contract Addresses is Test {
Removed. No longer used.

2024-01-26 18:08 UTC, bsolid commented on src/proposals/Addresses.sol
> +
Removed. No longer used.

2024-02-01 02:53 UTC, ElliotFriedman commented on src/Governance/Well.sol
> +        // }
remove commented code

2024-02-01 02:54 UTC, ElliotFriedman commented on src/Interfaces/IMToken.sol
> +interface IMToken {}
delete if unused

2024-02-01 02:54 UTC, ElliotFriedman commented on src/MErc20DelegateFixer.sol
> +    function fixUser(address liquidator, address user) public {
function should be marked external instead of public

2024-02-01 02:54 UTC, ElliotFriedman commented on src/MErc20DelegateFixer.sol
> +    function fixUser(address liquidator, address user) public {
```suggestion
    function fixUser(address liquidator, address user) external {
```

2024-02-01 02:56 UTC, ElliotFriedman commented on src/MErc20DelegateFixer.sol
> +    function getAccountTokens(address user) public view returns (uint256) {
```suggestion
    function getAccountTokens(address user) external view returns (uint256) {
```

Make function external instead of public if not called from within the contract

2024-02-01 03:14 UTC, ElliotFriedman commented on src/MErc20DelegateFixer.sol
> +        borrowSnapshot.principal = 0;
to maintain things as close as possible to how the repay function works which is what is called during a liquidation, and repay, we should set the interest index for this borrower to the current borrowIndex.

`borrowSnapshot.interestIndex = borrowIndex;`

2024-02-01 03:14 UTC, ElliotFriedman commented on src/MErc20DelegateMadFixer.sol
> +    function sweepAll(address sweeper) public {
```suggestion
    function sweepAll(address sweeper) external {
```

2024-02-01 03:15 UTC, ElliotFriedman commented on src/proposals/mips/mip-m17/mip-m17.sol
> +            "Upgrade MErc20Delegate for mFRAX"
```suggestion
            "Upgrade MErc20Delegate for mFRAX to MErc20DelegateFixer"
```

2024-02-01 03:16 UTC, ElliotFriedman commented on src/proposals/mips/mip-m17/mip-m17.sol
> +            "Upgrade MErc20Delegate for mxcDOT"
```suggestion
            "Upgrade MErc20Delegate for mxcDOT to MErc20DelegateFixer"
```

2024-02-01 03:18 UTC, ElliotFriedman commented on src/proposals/mips/mip-m17/mip-m17.sol
> +        // /// @dev set delegate for mFRAX
certain values that you use frequently in this build function, for example nomad reallocation multisig, mFRAX, mxcDOT, should be retrieved from the Addresses.sol object so you don't need to make a call each time you push a user onto the array to be liquidated

2024-02-01 03:18 UTC, ElliotFriedman commented on src/proposals/mips/mip-m17/mip-m17.sol
> +                            addresses.getAddress("NOMAD_REALLOCATION_MULTISIG"),
optimize, cache this variable

2024-02-01 03:18 UTC, ElliotFriedman commented on src/proposals/mips/mip-m17/mip-m17.sol
> +                        addresses.getAddress("MOONWELL_mFRAX"),
optimize, cache this variable

2024-02-01 03:21 UTC, ElliotFriedman commented on src/proposals/mips/mip-m17/mip-m17.sol
> +        _simulateActions(addresses.getAddress("ARTEMIS_GOVERNOR"), addresses.getAddress("WELL"), address(this));
please record the amount of gas this takes to run these actions. If we go over the 12.9m gas limit on Moonbeam, we may have to break this into multiple proposals.

https://book.getfoundry.sh/reference/forge-std/noGasMetering?highlight=gasleft#examples

start by getting gas left before and after simulations and that should give an idea of the cost to execute

2024-02-01 03:22 UTC, ElliotFriedman commented on test/integration/MErc20DelegateFixer.sol
> +contract MErc20DelegateFixerIntegrationTest is Test {
Rename file to `MErc20DelegateFixer.t.sol` to follow foundry convention

2024-02-01 03:23 UTC, ElliotFriedman commented on test/integration/MErc20DelegateMadFixer.sol
> +contract MErc20DelegateMadFixerIntegrationTest is Test {
style: file name should end with `.t.sol`

2024-02-01 03:23 UTC, ElliotFriedman commented on test/integration/proposals/mips/mip-m17/mip-m17.sol
> +contract MIPM17IntegrationTest is PostProposalCheck {
filename

2024-02-02 11:58 UTC, bsolid commented on src/proposals/mips/mip-m17/mip-m17.sol
> +        _simulateActions(addresses.getAddress("ARTEMIS_GOVERNOR"), addresses.getAddress("WELL"), address(this));
Using the example in that link, I see:

```
Gas Metering: 3334616
```

The simulation script also outputs:

```
Chain 1284

Estimated gas price: 198.860658767 gwei

Estimated total gas used for script: 2339258

Estimated amount required: 0.465186386905974886 ETH
```

Please note that this does not include the `DOT` actions. I will update these gas details once I can run those tests against a local node.

2024-02-03 19:14 UTC, ElliotFriedman commented on test/integration/MErc20DelegateFixer.t.sol
> +        vm.stopPrank();
this is the completely wrong way to do things.

Everything needs to operate off of a post proposal check.

At no point in any integration test should you be pranking in the setup to do an action that is performed in a governance proposal.

Pull in the PostProposalCheck file, run their setup, and you won't need to do this.

Apply this feedback to all of your integration tests, they should all be uniform, and all test exactly what happens after the proposal.

2024-02-03 19:15 UTC, ElliotFriedman commented on test/integration/MErc20DelegateFixer.t.sol
> +        delegator.fixUser(addresses.getAddress("NOMAD_REALLOCATION_MULTISIG"), _user);
it should be that only the governor can call this, and this contract should not be governor in integration tests

2024-02-03 19:35 UTC, ElliotFriedman requested changes

2024-02-03 19:35 UTC, ElliotFriedman commented on test/integration/MErc20DelegateFixer.t.sol
> +        assertTrue(delegator.totalReserves() > totalReserves);
why do reserves increase on a forced liquidation?

2024-02-03 19:35 UTC, ElliotFriedman commented on test/integration/MErc20DelegateFixer.t.sol
> +        assertEq(delegator.getAccountTokens(addresses.getAddress("NOMAD_REALLOCATION_MULTISIG")), 2264582);
there should not be any hardcoded values here, otherwise once the proposal passes, things will fail all over the place

2024-02-03 19:35 UTC, ElliotFriedman commented on test/integration/MErc20DelegateFixer.t.sol
> +        assertEq(delegator.totalSupply(), 13286905495267783);
remove hardcoded constant, move to variable asserting total supply before and after is unchanged

2024-02-03 19:35 UTC, ElliotFriedman commented on test/integration/MErc20DelegateFixer.t.sol
> +    function _borrowLiquidityShortfall() private {
these helper functions are littered throughout the file, it would be good to consolidate them into a single section to keep things organized

2024-02-03 19:35 UTC, ElliotFriedman commented on test/integration/MErc20DelegateFixer.t.sol
> +        assertEq(comptroller.borrowRewardSpeeds(1, addresses.getAddress("MOONWELL_mFRAX")), 1);
are these the same or different after the markets are unpaused and things are fixed?

2024-02-03 19:35 UTC, ElliotFriedman commented on test/integration/MErc20DelegateFixer.t.sol
> +        vm.stopPrank();
this is a really bad pattern, it makes the helper functions hard to reason about because it moves pre-conditions for them to work outside of the function itself

2024-02-03 19:35 UTC, ElliotFriedman commented on test/integration/MErc20DelegateFixer.t.sol
> +        vm.stopPrank();
fix

2024-02-03 19:35 UTC, ElliotFriedman commented on test/integration/MErc20DelegateFixer.t.sol
> +    function _repay() private {
this function name is misleading, its name should indicate it supplies, borrows and repays

2024-02-03 19:35 UTC, ElliotFriedman commented on test/integration/MErc20DelegateFixer.t.sol
> +        assertEq(delegator.repayBorrowBehalf(address(this), borrowAmount), 0);
assert state transitions are correct after the state transition happens

2024-02-03 19:35 UTC, ElliotFriedman commented on test/integration/MErc20DelegateFixer.t.sol
> +        assertEq(token.balanceOf(borrower), borrowAmount);
assert state transitions are correct after the state transition happens

2024-02-03 19:35 UTC, ElliotFriedman commented on test/integration/MErc20DelegateFixer.t.sol
> +        assertEq(token.balanceOf(borrower), borrowAmount);
assert state transitions are correct after the state transition happens

2024-02-03 19:35 UTC, ElliotFriedman commented on test/integration/MErc20DelegateFixer.t.sol
> +        delegator.repayBorrowBehalf(address(this), borrowAmount + 1_000e6);
assert state transitions are correct after the state transition happens

2024-02-03 19:35 UTC, ElliotFriedman commented on test/integration/MErc20DelegateFixer.t.sol
> +        assertEq(token.balanceOf(borrower), borrowAmount);
assert state transitions are correct after the state transition happens

2024-02-03 19:35 UTC, ElliotFriedman commented on test/integration/MErc20DelegateFixer.t.sol
> +        assertEq(delegator.redeem(balance), 0);
assert state transitions are correct after the state transition happens

totalSupply and userBalance both decrease

2024-02-03 19:35 UTC, ElliotFriedman commented on test/integration/MErc20DelegateFixer.t.sol
> +        assertEq(delegator.redeem(balance + 1_000e6), 9);
assert state transitions are correct after the state transition happens

2024-02-03 19:35 UTC, ElliotFriedman commented on test/integration/MErc20DelegateFixer.t.sol
> +
It would be great to see a single test that doesn't make use of helper functions clearly stepping through each and every step, asserting that state transitions are correct after the state transition happens, and then moving on to the next step. It might take a couple hundred lines of code, but that's fine. Let's be really explicit and make things as easy to follow as possible.

2024-02-03 19:35 UTC, ElliotFriedman commented on test/integration/MErc20DelegateFixer.t.sol
> +    function _liquidateBorrow() private {}
for this, you should be able to use the `deal(address(token), address(user), amount)` function to set a users mToken balance to be low, which then makes them eligible for liquidation.

2024-02-03 19:35 UTC, ElliotFriedman commented on test/integration/MErc20DelegateMadFixer.t.sol
> +        mwBTCMadDelegator._setImplementation(delegateAddress, false, emptyData);
same comment as other test, all of this as well as deployment of the fixer should go in the MIP-M17 file.

there should be no pranking or deployments in integration test setup function, that should all happen in the PostProposalCheck file.

2024-02-03 19:35 UTC, ElliotFriedman commented on test/integration/MErc20DelegateMadFixer.t.sol
> +
remove constants, check balances and totalSupply before and after to ensure no changes

2024-02-03 19:35 UTC, ElliotFriedman commented on test/integration/MErc20DelegateMadFixer.t.sol
> +        assertEq(mwETHMadDelegator.balanceOf(addresses.getAddress("NOMAD_REALLOCATION_MULTISIG")), 24519061554277751182);
remove hardcoded values

2024-02-03 19:35 UTC, ElliotFriedman commented on test/integration/MErc20DelegateMadFixer.t.sol
> +        assertEq(mwETHMadDelegator.balanceOf(addresses.getAddress("NOMAD_REALLOCATION_MULTISIG")), 24519061554277751182);
just check pre and post and ensure post balance is 0, and pre-balance goes to reallocation multisig

2024-02-03 19:35 UTC, ElliotFriedman commented on test/integration/proposals/mips/mip-m17/mip-m17.t.sol
> +    }
This is how all integration tests around this proposal should be structured

2024-02-03 19:35 UTC, ElliotFriedman commented on test/integration/proposals/mips/mip-m17/mip-m17.t.sol
> +        assertEq(comptroller.supplyRewardSpeeds(1, address(delegator)), 6952629629629629);
the constants should be fine

2024-02-03 19:52 UTC, ElliotFriedman commented on test/integration/MErc20DelegateFixer.t.sol
> +        assertEq(delegator.getAccountTokens(addresses.getAddress("NOMAD_REALLOCATION_MULTISIG")), 2264582);
I guess in this case, it's fine because these values aren't changing, but maybe move the constants into a variable at the top of the file to keep track of things.

2024-02-03 19:53 UTC, ElliotFriedman commented on test/integration/MErc20DelegateFixer.t.sol
> +        assertTrue(delegator.totalReserves() > totalReserves);
we should assert that totalBorrows decreased exactly by the amount fixed

2024-02-05 09:36 UTC, bsolid commented on test/integration/MErc20DelegateFixer.t.sol
> +        vm.stopPrank();
Updated as per our earlier discussion.

2024-02-05 09:36 UTC, bsolid commented on test/integration/MErc20DelegateFixer.t.sol
> +        delegator.fixUser(addresses.getAddress("NOMAD_REALLOCATION_MULTISIG"), _user);
Updated as per our earlier discussion.

2024-02-05 09:37 UTC, bsolid commented on test/integration/MErc20DelegateFixer.t.sol
> +        assertEq(delegator.getAccountTokens(addresses.getAddress("NOMAD_REALLOCATION_MULTISIG")), 2264582);
Updated as per our earlier discussion.

2024-02-05 09:38 UTC, bsolid commented on test/integration/MErc20DelegateFixer.t.sol
> +        assertEq(comptroller.borrowRewardSpeeds(1, addresses.getAddress("MOONWELL_mFRAX")), 1);
For different reward types (`WELL` and `GLMR`). Have updated as per our earlier discussion.

2024-02-05 09:38 UTC, bsolid commented on test/integration/MErc20DelegateMadFixer.t.sol
> +        mwBTCMadDelegator._setImplementation(delegateAddress, false, emptyData);
Updated as per our earlier discussion.

2024-02-05 09:38 UTC, bsolid commented on test/integration/MErc20DelegateMadFixer.t.sol
> +        assertEq(mwETHMadDelegator.balanceOf(addresses.getAddress("NOMAD_REALLOCATION_MULTISIG")), 24519061554277751182);
Updated as per our earlier discussion.

2024-02-05 09:39 UTC, bsolid commented on test/integration/MErc20DelegateMadFixer.t.sol
> +
Updated as per our earlier discussion.

2024-02-05 11:35 UTC, bsolid commented on test/integration/MErc20DelegateFixer.t.sol
> +        assertTrue(delegator.totalReserves() > totalReserves);
Have made changes to such calculations and moved into the proposal integration test.

2024-02-05 11:35 UTC, bsolid commented on test/integration/MErc20DelegateFixer.t.sol
> +    function _repay() private {
Updated all test functions to be much clearer in what is being tested.

2024-02-05 11:36 UTC, bsolid commented on test/integration/MErc20DelegateFixer.t.sol
> +        assertEq(delegator.repayBorrowBehalf(address(this), borrowAmount), 0);
Done.

2024-02-05 11:36 UTC, bsolid commented on test/integration/MErc20DelegateFixer.t.sol
> +        assertEq(token.balanceOf(borrower), borrowAmount);
Done.

2024-02-05 11:36 UTC, bsolid commented on test/integration/MErc20DelegateFixer.t.sol
> +        delegator.repayBorrowBehalf(address(this), borrowAmount + 1_000e6);
Done.

2024-02-05 11:36 UTC, bsolid commented on test/integration/MErc20DelegateFixer.t.sol
> +        assertEq(token.balanceOf(borrower), borrowAmount);
Done.

2024-02-05 12:02 UTC, bsolid commented on test/integration/MErc20DelegateFixer.t.sol
> +
Copy that. Things should be a bit clearer now, with all the other feedback I've incorporated/changes I've made.

2024-02-06 18:53 UTC, ElliotFriedman commented on src/MErc20DelegateMadFixer.sol
> +        token.transferFrom(address(this), sweeper, amount);
we can just do a `.transfer` here instead of a `transferFrom` and remove the `approve` call.

2024-02-06 18:56 UTC, ElliotFriedman commented on src/proposals/mips/mip-m17/mip-m17.sol
> +                        "Liquidate bad mFRAX debt"
let's change this description to

`string(abi.encodePacked("Liquidate bad mFRAX debt for user: ", mFRAXDebtors[i].addr)`

so that it includes the address of the user getting liquidated in the description

2024-02-06 18:56 UTC, ElliotFriedman commented on src/proposals/mips/mip-m17/mip-m17.sol
> +                        "Liquidate bad mxcDOT debt"
let's change this description to

string(abi.encodePacked("Liquidate bad mxcDOT debt for user: ", mxcDOTDebtors[i].addr)

so that it includes the address of the user getting liquidated in the description

2024-02-06 18:58 UTC, ElliotFriedman commented on src/proposals/mips/mip-m17/mip-m17.sol
> +        _simulateActions(addresses.getAddress("ARTEMIS_GOVERNOR"), addresses.getAddress("WELL"), address(this));
ok, ty for that

2024-02-12 21:29 UTC, ElliotFriedman commented on src/MErc20DelegateFixer.sol
> +
add repayBadDebt function

2024-02-13 17:08 UTC, anajuliabit requested changes

2024-02-13 17:08 UTC, anajuliabit commented on .github/workflows/test.yml
Could we include in the file name that this workflow is only related to tests fixing bad debt?

2024-02-13 17:08 UTC, anajuliabit commented on src/MErc20DelegateFixer.sol
> +        accountTokens[user] = 0;
this could be done within the if below

2024-02-13 17:08 UTC, anajuliabit commented on src/proposals/mips/mip-m17/MIP-M17.md
> +This proposal will remove all collateral mTokens from users with bad debt from all markets, sending them to the community multisig. In order to allow mToken collateral sweeping and bad debt write off
```suggestion
This proposal will remove all collateral mTokens from users with bad debt from all markets, sending them to the community multisig. In order to allow mToken collateral sweeping and bad debt write-offs, the mTokens will have their implementations upgraded. This will stop further issues and allow the exchange rates of the assets to stay the same post-proposal. Interest Rate Models may need to be changed in order to stop rate spikes due to changes in supply and borrow amounts.
```

2024-02-13 17:08 UTC, anajuliabit commented on src/proposals/mips/mip-m17/mip-m17.sol
> +            "MERC20_DELEGATE_FIXER_NOMAD_LOGIC",
``` suggestion
            "MERC20_BAD_DEBT_DELEGATE_FIXER_NOMAD_LOGIC",
```

I prefer this way for consistency, but it's up to you to decide whether to remediate or not.

2024-02-13 17:08 UTC, anajuliabit commented on test/integration/PostProposalCheck.sol
> +        suite.setDebug(false);
default is false so no need to call setDebug here

2024-02-13 17:08 UTC, anajuliabit commented on src/proposals/mips/mip-m17/mip-m17.sol
>      function _validate(Addresses addresses, address) internal override {
could we also make sure that the contracts were upgraded here? you could reuse this https://github.com/moonwell-fi/moonwell-contracts-v2/pull/101/files#diff-82d896bade237944e80776433269ce432b75f90e71c4ccb6e30c55d6eeb12898

2024-02-13 17:09 UTC, anajuliabit commented on .github/workflows/test.yml
never mind, I thought this repo was moonwell-contracts-v2

2024-02-13 21:31 UTC, ElliotFriedman commented on src/MErc20DelegateFixer.sol
> +
add repayBadDebt with reserves function

2024-02-15 23:09 UTC, ElliotFriedman commented on src/proposals/mips/mip-m17/mip-m17.sol
>      function _validate(Addresses addresses, address) internal override {
I don't think that exact code will work because this is not a transparent proxy patter, so the slot for the admin will be different.

However, we do have the slots in this PR from the slither run.

2024-02-15 23:12 UTC, ElliotFriedman commented on src/proposals/mips/mip-m17/mip-m17.sol
>      function _validate(Addresses addresses, address) internal override {
https://github.com/moonwell-fi/mtoken-fixes/pull/1/files#diff-0ff9acb37d91fb6aa8d353a4f77a19afe566e041d2c85570d593fe9e594e5a40R282-R303

<img width="749" alt="Screenshot 2024-02-15 at 3 12 10 PM" src="https://github.com/moonwell-fi/mtoken-fixes/assets/34463580/ec9c8ecd-b063-463f-8bbd-8884faef0d1b">

2024-02-15 23:13 UTC, ElliotFriedman commented on src/MErc20DelegateFixer.sol
> +        accountTokens[user] = 0;
done

2024-02-15 23:27 UTC, ElliotFriedman commented on test/integration/PostProposalCheck.sol
> +        suite.setDebug(false);
removed

2024-02-20 01:00 UTC, merged